In [169]:
import pandas as pd
Report={
    "Name":["Riya","Rahul","Ravi","Shruti","Samar","Sahil","Rajat","Khushi","Krishna","Aryan"],
    "Age":[19,17,29,28,16,14,23,34,19,15],
    "Email-id":["Riya@hotmail.com","Rahul@read.com","Ravi@wade-garner.com","Shruti@gmail.com"
    ,"samar@yahoo.com","Sahil@olson-robinson.com","Rajat@smith.com","Khushi@gmail.com","Krish@wade-garner.com","Arya@yahoo.com"],
    "Phone-Number":[9089899078,8797780989,9234562312,9867453445,8767986790,6789786669,9997778885,
    9787678888,7777677789,9078877898],
    "Company-Name":["Microsoft","Google","Amazon","Uber","Zomato","Swiggy","Flipcart",
    "Myntra","Apple","Infosys"],
    "Salary(LPA)":[4000000,3800000,3000000,2900000,2500000,3700000,1800000,2800000,1200000,1000000],
    "Payment-Card":["MasterCard","Rupay","Visa","PayPal","Sage","Maestro","Discover",
    "ebay","Cirrus","MasterCard"],
    "Expiration-date(Credit-card)":[2025,2028,2039,2022,2022,2022,2024,2025,2026,2029]
}
x=pd.DataFrame(Report)
x

,Name,Age,Email-id,Phone-Number,Company-Name,Salary(LPA),Payment-Card,Expiration-date(Credit-card)
0,Riya,19,Riya@hotmail.com,9089899078,Microsoft,4000000,MasterCard,2025
1,Rahul,17,Rahul@read.com,8797780989,Google,3800000,Rupay,2028
2,Ravi,29,Ravi@wade-garner.com,9234562312,Amazon,3000000,Visa,2039
3,Shruti,28,Shruti@gmail.com,9867453445,Uber,2900000,PayPal,2022
4,Samar,16,samar@yahoo.com,8767986790,Zomato,2500000,Sage,2022
5,Sahil,14,Sahil@olson-robinson.com,6789786669,Swiggy,3700000,Maestro,2022
6,Rajat,23,Rajat@smith.com,9997778885,Flipcart,1800000,Discover,2024
7,Khushi,34,Khushi@gmail.com,9787678888,Myntra,2800000,ebay,2025
8,Krishna,19,Krish@wade-garner.com,7777677789,Apple,1200000,Cirrus,2026
9,Aryan,15,Arya@yahoo.com,9078877898,Infosys,1000000,MasterCard,2029

In [170]:
x.to_csv('SData.csv')

Display top 5 data of Dataset

In [171]:
x.head(5)

,Name,Age,Email-id,Phone-Number,Company-Name,Salary(LPA),Payment-Card,Expiration-date(Credit-card)
0,Riya,19,Riya@hotmail.com,9089899078,Microsoft,4000000,MasterCard,2025
1,Rahul,17,Rahul@read.com,8797780989,Google,3800000,Rupay,2028
2,Ravi,29,Ravi@wade-garner.com,9234562312,Amazon,3000000,Visa,2039
3,Shruti,28,Shruti@gmail.com,9867453445,Uber,2900000,PayPal,2022
4,Samar,16,samar@yahoo.com,8767986790,Zomato,2500000,Sage,2022

Check Last 5 Rows in Dataset

In [172]:
x.tail(5)

,Name,Age,Email-id,Phone-Number,Company-Name,Salary(LPA),Payment-Card,Expiration-date(Credit-card)
5,Sahil,14,Sahil@olson-robinson.com,6789786669,Swiggy,3700000,Maestro,2022
6,Rajat,23,Rajat@smith.com,9997778885,Flipcart,1800000,Discover,2024
7,Khushi,34,Khushi@gmail.com,9787678888,Myntra,2800000,ebay,2025
8,Krishna,19,Krish@wade-garner.com,7777677789,Apple,1200000,Cirrus,2026
9,Aryan,15,Arya@yahoo.com,9078877898,Infosys,1000000,MasterCard,2029

Check DataType of each column in Dataset

In [173]:
x.dtypes

Name                            object
Age                              int64
Email-id                        object
Phone-Number                     int64
Company-Name                    object
Salary(LPA)                      int64
Payment-Card                    object
Expiration-date(Credit-card)     int64
dtype: object

Check Null Values in Dataset

In [174]:
x.isnull().sum()

Name                            0
Age                             0
Email-id                        0
Phone-Number                    0
Company-Name                    0
Salary(LPA)                     0
Payment-Card                    0
Expiration-date(Credit-card)    0
dtype: int64

How many rows and columns in Dataset?

In [175]:
len(x.columns)

8

In [176]:
len(x)

10

Highest and Lowest salary

In [177]:
x.columns

Index(['Name', 'Age', 'Email-id', 'Phone-Number', 'Company-Name',
       'Salary(LPA)', 'Payment-Card', 'Expiration-date(Credit-card)'],
      dtype='object')

In [178]:
x['Salary(LPA)'].max()

4000000

In [179]:
x["Salary(LPA)"].min()

1000000

Average Salary(LPA)

In [180]:
x['Salary(LPA)'].mean()

2670000.0

How many peoples have same age?

In [181]:
x.columns

Index(['Name', 'Age', 'Email-id', 'Phone-Number', 'Company-Name',
       'Salary(LPA)', 'Payment-Card', 'Expiration-date(Credit-card)'],
      dtype='object')

In [182]:
x[x['Age']==19]

,Name,Age,Email-id,Phone-Number,Company-Name,Salary(LPA),Payment-Card,Expiration-date(Credit-card)
0,Riya,19,Riya@hotmail.com,9089899078,Microsoft,4000000,MasterCard,2025
8,Krishna,19,Krish@wade-garner.com,7777677789,Apple,1200000,Cirrus,2026

In [183]:
len(x[x['Age']==19])

2

How many people have Job title Microsoft?

In [184]:
len(x[x['Company-Name'].str.contains('Microsoft',case=False)])

1

Find email of the Person have following Company-Name "Amazon"

In [185]:
x.columns

Index(['Name', 'Age', 'Email-id', 'Phone-Number', 'Company-Name',
       'Salary(LPA)', 'Payment-Card', 'Expiration-date(Credit-card)'],
      dtype='object')

In [186]:
x[x['Company-Name']=="Amazon"]["Email-id"]

2    Ravi@wade-garner.com
Name: Email-id, dtype: object

How many persons have mastercard and made a purchase above 1500000?

In [187]:
x.columns

Index(['Name', 'Age', 'Email-id', 'Phone-Number', 'Company-Name',
       'Salary(LPA)', 'Payment-Card', 'Expiration-date(Credit-card)'],
      dtype='object')

In [188]:
x[(x['Payment-Card']=='MasterCard') & (x['Salary(LPA)']>1500000)]

,Name,Age,Email-id,Phone-Number,Company-Name,Salary(LPA),Payment-Card,Expiration-date(Credit-card)
0,Riya,19,Riya@hotmail.com,9089899078,Microsoft,4000000,MasterCard,2025

In [189]:
len(x[(x['Payment-Card']=='MasterCard') & (x['Salary(LPA)']>1500000)])

1

Find email of the person who age is 19?

In [190]:
x.columns

Index(['Name', 'Age', 'Email-id', 'Phone-Number', 'Company-Name',
       'Salary(LPA)', 'Payment-Card', 'Expiration-date(Credit-card)'],
      dtype='object')

In [191]:
x[x['Age']==19]['Email-id']

0         Riya@hotmail.com
8    Krish@wade-garner.com
Name: Email-id, dtype: object

How many persons have credit-card that expires in 2022?

In [192]:
x[x['Expiration-date(Credit-card)']==2022]

,Name,Age,Email-id,Phone-Number,Company-Name,Salary(LPA),Payment-Card,Expiration-date(Credit-card)
3,Shruti,28,Shruti@gmail.com,9867453445,Uber,2900000,PayPal,2022
4,Samar,16,samar@yahoo.com,8767986790,Zomato,2500000,Sage,2022
5,Sahil,14,Sahil@olson-robinson.com,6789786669,Swiggy,3700000,Maestro,2022

In [193]:
len(x[x['Expiration-date(Credit-card)']==2022])

3

Find person who has 5 top email-id like @gmail.com,@yahoo.com.....?

In [197]:
list=[]
for email in x['Email-id']:
    email.split('@')
x['Email-id'].head(5)

0        Riya@hotmail.com
1          Rahul@read.com
2    Ravi@wade-garner.com
3        Shruti@gmail.com
4         samar@yahoo.com
Name: Email-id, dtype: object